name: tricycall_thesis
description: A Ride Hailing Flutter Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  fl_country_code_picker: ^0.1.2
  pinput: ^2.2.31
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  image_picker: ^0.8.7+4
  cloud_firestore: ^4.6.0
  firebase_storage: ^11.1.2
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.4.0+8
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_typeahead: ^4.3.8
  flutter_launcher_icons: ^0.13.1
  alt_sms_autofill: ^1.0.0
  permission_handler: ^10.2.0
  shared_preferences: ^2.1.1
  flutter_polyline_points: ^1.0.0
  indexed: ^0.0.8
  group_radio_button: ^1.3.0
  loading_animation_widget: ^1.2.0+4
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.11
  paymongo_sdk: ^1.6.1
  timer_count_down: ^2.2.2
  file_picker: ^5.3.0
  cloud_functions: ^4.3.1
  firebase_messaging: ^14.6.1
  flutter_local_notifications: ^14.1.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_luncher.png"
  background_color: "#ffffff"
  theme_color: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_luncher.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo_luncher.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_luncher.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

