// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGBVyd87PYzdP26HmcFLWToPC_koOOiVQ',
    appId: '1:503233099147:web:7a7fd57fe110ad3dd52b8e',
    messagingSenderId: '503233099147',
    projectId: 'tricycallthesis',
    authDomain: 'tricycallthesis.firebaseapp.com',
    storageBucket: 'tricycallthesis.appspot.com',
    measurementId: 'G-WX87SMQK8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUCqw4Am8gfSmKDEUNu-0vpXMc5d8Ilw',
    appId: '1:503233099147:android:dfffd791f943c8ccd52b8e',
    messagingSenderId: '503233099147',
    projectId: 'tricycallthesis',
    storageBucket: 'tricycallthesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8DzM0YYYX6GccbxTsrdBl3u5OMBq4w-c',
    appId: '1:503233099147:ios:d25d491ce05803f0d52b8e',
    messagingSenderId: '503233099147',
    projectId: 'tricycallthesis',
    storageBucket: 'tricycallthesis.appspot.com',
    androidClientId: '503233099147-ffjofs5ueo6k3n4qhrfr37cvi8sbt3kk.apps.googleusercontent.com',
    iosClientId: '503233099147-i1mvmmhju2obj1c9m86qr5e2gdk21ttc.apps.googleusercontent.com',
    iosBundleId: 'com.reydan.tricycallThesis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8DzM0YYYX6GccbxTsrdBl3u5OMBq4w-c',
    appId: '1:503233099147:ios:d25d491ce05803f0d52b8e',
    messagingSenderId: '503233099147',
    projectId: 'tricycallthesis',
    storageBucket: 'tricycallthesis.appspot.com',
    androidClientId: '503233099147-ffjofs5ueo6k3n4qhrfr37cvi8sbt3kk.apps.googleusercontent.com',
    iosClientId: '503233099147-i1mvmmhju2obj1c9m86qr5e2gdk21ttc.apps.googleusercontent.com',
    iosBundleId: 'com.reydan.tricycallThesis',
  );
}
